### ISSUE TITLE
unknown

### ISSUE THREAD

**Issue by jon2180** [shoubai/blog#1]
https://github.com/shoubai/ComputerGraph/blob/47eec6c6038867c0f609ed4505c209b8326f293d/README.md?plain=1#L1

touch fishes

**Comment by shoubai** [comment]
哈哈哈哈哈哈 摸鱼是吧



---Original---
From: "Jon ***@***.***&gt;
Date: Tue, Mar 1, 2022 15:31 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [shoubai/ComputerGraph] unknown (Issue #1)




 
https://github.com/shoubai/ComputerGraph/blob/47eec6c6038867c0f609ed4505c209b8326f293d/README.md?plain=1#L1
 
touch fishes
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jon2180** [comment]
what are you doing now? be busy or be lazy?  Why could you comment the issue directly by email.

I have experienced a dark period, as the overtime work is required.

There are 2.2 hours left by getting off work. I am counting seconds now.

**Comment by shoubai** [comment]
I fired my boss yesterday.
I can't stand low salary and terrible envoriment.
Of cause I find a new job, now i am work as a software testing engineer in Wuhou.
Today is the first day, my colleage working at home because of epidemic.
As for that new respiratory, i am trying to build some github pages to record something.
And what's your plan? emmmm......leave ChengDu to east of China?
Too boring~~ I hope i can keep this state for next week.&nbsp;
It's 1h12min before get off work.&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shoubai/ComputerGraph"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 下午3:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shoubai/ComputerGraph] unknown (Issue #1)





 
what are you doing now? be busy or be lazy?  Why could you comment the issue directly by email.
 
I have experienced a dark period, as the overtime work is required.
 
There are 2.2 hours left by getting off work. I am counting seconds now.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jon2180** [comment]
New job? It sounds nice.

As I known, Jun xxou, Jiaxx Li (Blur) have found a Software Testing Engineer job.  You joined the team too. Are you staying home and working remotely now?

We can make everything terrific with persistent. I have a expectation of reading the articles you shared.

I want to find a new city where I continue my work. At present, I am trying to find a new xxx. Actually, it is unsettled. I have no work experience and am not prepared for the incoming interview. HRs recommend me to keep in FE domain.

51 minutes left.

**Comment by shoubai** [comment]
Yeah, Jiayi and Jun Bro told we are testing team too.

I am in my company now. Green hand, you konw, always cautiously.

As for job, actually work experience is also cannot be ignored factors. xinxin is still finding job in ChengDu. But he haven't&nbsp; work experience, even he went to interview, the interviewer just give him a little time to show himself.&nbsp;

So, if I working in this new company comfortable, I will recommend him come to here.

Don't be worry, I think you can join in Tencent or other nice company by your effort. But now, you can talk with your leader to discuss your salary. If they refuse, get ready to step out of your comfort zone.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shoubai/ComputerGraph"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shoubai/ComputerGraph] unknown (Issue #1)





 
New job? It sounds nice.
 
As I known, Jun xxou, Jiaxx Li (Blur) have found a Software Testing Engineer job.  You joined the team too. Are you staying home and working remotely now?
 
We can make everything terrific with persistent. I have a expectation of reading the articles you shared.
 
I want to find a new city where I continue my work. At present, I am trying to find a new xxx. Actually, it is unsettled. I have no work experience and am not prepared for the incoming interview. HRs recommend me to keep in FE domain.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jon2180** [comment]
How is the experience in software testing team? with great amount of business work or not? Does it have much many knowledge to learn? such as scripting, service logic, communications?

By the way, where is Xingxing living?

The fact that I want to find a new job is not only because I want earn more salary, but also I am looking forward to leave Front End domain and do something closer to Computer Science.  I have given up asking leader for raising salary.

Presently, Tencent ltd. and some other company in same scale is so far away for me. I am the talent they will never get for the next three years. Yes, I am.

Yesterday, I finished two quizzes. First quiz took me three hours about, last one lasted 40 minutes. That give me a impression that there are much knowledge to learn and a lot of utilities, facilities and frameworks to try. I`ll put more efforts.

Hope to find a ideal job.

Share you life.

**Comment by shoubai** [comment]
Today, I am going to ChengFei research institute. Actually, my job is assist them to do some trifling matters. After that, I will go back to my company.&nbsp; Software testing is boring and it doesnt help me much, I am more interested in C/C++.
Wooooooow, I seems to choose another way. I just want to earn more money for my dad's&nbsp;disease. A good news is that my dad's disease is controled. He can lives more time with me. So I show you this hopeful news.
XinXin is living in ZhongHai, not far from school. This morning, he receive an invitation from a company which he works last year.
I think you will join in nice company if you study continue, but I suggest you take care more on your health.
Good Luck for you.

---Original---
From: "Jon ***@***.***&gt;
Date: Thu, Mar 3, 2022 16:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [shoubai/ComputerGraph] unknown (Issue #1)




 
How is the experience in software testing team? with great amount of business work or not? Does it have much many knowledge to learn? such as scripting, service logic, communications
 
By the way, where is Xingxing living?
 
The fact that I want to find a new job is not only because I want earn more salary, but also I am looking forward to leave Front End domain and do something closer to Computer Science.  I have given up asking leader for raising salary.
 
Presently, Tencent ltd. and some other company in same scale is so far away for me. I am the talent they will never get for the next three years. Yes, I am.
 
Yesterday, I finished two quizzes. First quiz took me three hours about, last one lasted 40 minutes. That give me a impression that there are much knowledge to learn and a lot of utilities, facilities and frameworks to try. I`ll put more efforts.
 
Hope to find a ideal job.
 
Share you life.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jon2180** [comment]
I found that it was 26 days ago we chatted on GitHub last time. Time elapsed as so fast. These are 2 days left in this company. And I am waiting for the committer to merge my pull requests to mainline branch to solve some problems now. I am a little bit sleepy.

**Comment by shoubai** [comment]
HAHAHA


Coincidentally, I'm back here, the same place, the same chatting way.



Because of the Epidemic situation in ChengDU. These days i will work in my company. And I will have more time to study.


I thought you were working for the new company. Or Did i misunderstand you? Are you working in YiBao still?


And my blog update some new things, if you want to be in the spirit, try to read my blog. Maybe, you will wake up and laugh.


https://shoubai.github.io/blog


---Original---
From: "Jon ***@***.***&gt;
Date: Tue, Mar 29, 2022 16:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [shoubai/blog] unknown (Issue #1)




 
I found that it was 26 days ago we chatted on GitHub last time. Time elapsed as so fast. These are 2 days left in this company. And I am waiting for the committer to merge my pull requests to mainline branch to solve some problems now. I am a little bit sleepy.

**Comment by jon2180** [comment]
Yeah, the same place, the same way.

At first, Answer in Chinese：在旧公司的时间还剩两天。

Actually, I have read your blogs about art, philosophy, and file reviews. You write your feelings. It is a nice beginning. The site has a nice theme(a little bit like powering by Vuepress).  I think the opinions which belong to yourself are very terrific.

My git-page is powered by Vuepress too and has not been updated in a long time. 

I bought a domain name `showmecode.cc` fourteen days ago and sent a registration request to authority. This is my first time. I think the domain name is very cool for programmers. Maybe the registration will be finished successfully in some days.

**Comment by shoubai** [comment]
HAHAHA&nbsp;
Of course, the blog theme is powered by Vuepress. I like this theme and style, clear, simple, without any extra informations.&nbsp;
And I am very interested in your site too. This name is meaningful for programmers, like the theme I used.
I preper to study in EE. Now, I am reading a book named Foundations of Analog and Digital Electronic Circuits. I will update my reading though in blog.
Keep in touch and have a nice day.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jon ***@***.***&gt;; 
发送时间: 2022年3月29日(星期二) 晚上9:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shoubai/blog] unknown (Issue #1)





 
Yeah, the same place, the same way.
 
At first, Answer in Chinese：在旧公司的时间还剩两天。
 
Actually, I have read your blogs about art, philosophy, and file reviews. You write your feelings. It is a nice beginning. The site has a nice theme(a little bit like powering by Vuepress).  I think the opinions which belong to yourself are very terrific.
 
My git-page is powered by Vuepress too and has not been updated in a long time.
 
I bought a domain name showmecode.cc fourteen days ago and sent a registration request to authority. This is my first time. I think the domain name is very cool for programmers. Maybe the registration will be finished successfully in some days.
